import json
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM


# ---------------------------------------------------------
# 1. CONFIGURATION
# ---------------------------------------------------------

# Instruction-tuned Qwen model used for document-grounded QA.
model_name = "Qwen/Qwen2.5-1.5B-Instruct"


# Input file containing the cleaned/preprocessed document.
#
# This file was created by the earlier HTML preprocessing
# stage and contains data conceptually like:
#
# [
#     {
#         "text": "Cleaned document text..."
#     }
# ]
text_file = "text_preprocessed.json"


# This script will CREATE / OVERWRITE this file every time
# it runs.
#
# Therefore we no longer depend on text_tokenized.json
# having been generated by a previous tokenization script.
tokenized_text_file = "text_tokenized.json"


# Maximum number of NEW tokens Qwen may generate
# for its answer.
max_new_tokens = 150


# ---------------------------------------------------------
# 2. SELECT CPU OR GPU
# ---------------------------------------------------------

# Use CUDA automatically when it is available.
#
# Otherwise fall back to CPU.
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using device:", device)


# ---------------------------------------------------------
# 3. LOAD THE QWEN TOKENIZER
# ---------------------------------------------------------

print("Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

print("Tokenizer loaded.")


# ---------------------------------------------------------
# 4. READ THE PREPROCESSED DOCUMENT FILE
# ---------------------------------------------------------

# Unlike the original GPT-2 script:
#
#     text = f.read()
#
# we use json.load().
#
# That is important because text_preprocessed.json is
# structured JSON.
#
# Example:
#
# [
#     {
#         "text": "Actual document content..."
#     }
# ]
#
# Using json.load() lets us extract only the actual
# document text instead of tokenizing JSON syntax such as:
#
#     [
#     {
#     "text":
#     }
#     ]
with open(text_file, "r", encoding="utf-8") as f:
    data = json.load(f)


# ---------------------------------------------------------
# 5. COMBINE THE DOCUMENT TEXT
# ---------------------------------------------------------

# There may potentially be more than one dictionary
# inside the JSON file.
#
# Extract every "text" value and combine them into one
# document.
#
# If there is only one entry, this simply returns that
# document's text.
document_text = "\n".join(
    item["text"] for item in data
)


# ---------------------------------------------------------
# 6. TOKENIZE THE DOCUMENT FRESH
# ---------------------------------------------------------

print("Tokenizing document...")


# Convert the document into Qwen token IDs.
#
# add_special_tokens=False:
#
# We are tokenizing the DOCUMENT itself here.
#
# Qwen's conversational/system/user special tokens will
# later be added correctly by apply_chat_template().
#
# We therefore do not want to add standalone sequence
# special tokens to the document at this stage.
document_token_ids = tokenizer.encode(
    document_text,
    add_special_tokens=False,
)


print("Document tokenized.")


# ---------------------------------------------------------
# 7. WRITE THE FRESH TOKENIZATION TO DISK
# ---------------------------------------------------------

# Save the Qwen token IDs to text_tokenized.json.
#
# If the file already exists, "w" overwrites it.
#
# This means every run produces a fresh tokenization based
# on:
#
#     current text_preprocessed.json
#              +
#     current Qwen tokenizer
with open(tokenized_text_file, "w", encoding="utf-8") as f:

    json.dump(
        document_token_ids,
        f,
        ensure_ascii=False,
    )


print(
    f"Tokenized document saved to {tokenized_text_file}"
)


# ---------------------------------------------------------
# 8. LOAD THE TOKENIZED DOCUMENT BACK FROM DISK
# ---------------------------------------------------------

# This mirrors the structure of the GPT-2 script you shared:
#
#     tokenize
#        ↓
#     write JSON
#        ↓
#     read JSON again
#
#
# This isn't strictly necessary because we already have
# document_token_ids in memory.
#
# But we retain this pattern so that text_tokenized.json
# represents the exact persisted token data used by the
# remainder of the script.
with open(tokenized_text_file, "r", encoding="utf-8") as f:
    text_tokens = json.load(f)


# ---------------------------------------------------------
# 9. CONVERT THE TOKEN IDS BACK TO DOCUMENT TEXT
# ---------------------------------------------------------

# Qwen's chat template expects text messages.
#
# Therefore we convert the freshly generated token IDs
# back into text before placing the document inside the
# user message.
#
# Conceptually:
#
# text_preprocessed.json
#       ↓
# Qwen tokenizer
#       ↓
# token IDs
#       ↓
# text_tokenized.json
#       ↓
# load token IDs
#       ↓
# decode
#       ↓
# document supplied to Qwen
#
#
# This ensures that the document used for inference is
# derived from the freshly generated tokenized file.
document_text_from_tokens = tokenizer.decode(
    text_tokens,
    skip_special_tokens=True,
)


# ---------------------------------------------------------
# 10. LOAD THE QWEN MODEL
# ---------------------------------------------------------

print("Loading model...")


# attn_implementation="eager" is retained because the
# optimized SDPA CUDA implementation previously produced:
#
#     CUDA error: device-side assert triggered
#
# in this environment.
#
# Using eager attention resolved that issue.
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    attn_implementation="eager",
)


# Move the model onto the selected device.
model = model.to(device)


# Put the model into inference mode.
model.eval()


print("Model loaded.")


# ---------------------------------------------------------
# 11. DEFINE THE QUESTION
# ---------------------------------------------------------

question = (
    "How has the understanding of the term religion "
    "evolved over time?"
)


# ---------------------------------------------------------
# 12. CREATE THE SYSTEM + USER MESSAGES
# ---------------------------------------------------------

# Qwen2.5-Instruct is an instruction-tuned/chat model.
#
# We therefore use its expected conversational format.
#
#
# SYSTEM MESSAGE:
#
# Tells the model HOW it should behave.
#
#
# USER MESSAGE:
#
# Provides:
#
#     document
#     +
#     question
#
#
# Notice that we use:
#
#     document_text_from_tokens
#
# rather than the original document_text.
#
# That means the actual document reaching Qwen came from
# the freshly generated text_tokenized.json file.
messages = [
    {
        "role": "system",
        "content": (
            "You are a document question-answering assistant. "
            "Answer the question using only information contained "
            "in the supplied document. "
            "Do not use outside knowledge. "
            "If the document does not contain enough information "
            "to answer the question, respond exactly with: "
            "'The answer is not available in the document.' "
            "Keep the answer concise and directly relevant "
            "to the question."
        ),
    },
    {
        "role": "user",
        "content": (
            f"Document:\n"
            f"{document_text_from_tokens}\n\n"
            f"Question:\n"
            f"{question}"
        ),
    },
]


# ---------------------------------------------------------
# 13. APPLY QWEN'S CHAT TEMPLATE
# ---------------------------------------------------------

# apply_chat_template() formats the messages using the
# special tokens expected by Qwen.
#
# We should let the tokenizer do this rather than manually
# inventing:
#
#     SYSTEM:
#     USER:
#     ASSISTANT:
#
# formatting.
#
#
# tokenize=False:
#
# Return formatted text at this stage.
#
#
# add_generation_prompt=True:
#
# Add the special marker indicating:
#
#     "Qwen should now generate the assistant response."
prompt = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True,
)


# ---------------------------------------------------------
# 14. TOKENIZE THE COMPLETE QA PROMPT
# ---------------------------------------------------------

# Now tokenize:
#
#     system instruction
#          +
#     document
#          +
#     question
#          +
#     assistant generation marker
#
# into the actual model input.
inputs = tokenizer(
    prompt,
    return_tensors="pt",
)


# Move all tensors onto the same device as the model.
inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}


# ---------------------------------------------------------
# 15. INSPECT TOKEN COUNTS
# ---------------------------------------------------------

# Number of tokens in the standalone document.
document_token_count = len(text_tokens)


# Number of tokens in the COMPLETE model prompt.
#
# This includes:
#
#     system instruction
#     chat-template tokens
#     document
#     question
#     assistant-generation marker
input_token_count = inputs["input_ids"].shape[1]


# Maximum context size supported by the model.
model_context_length = model.config.max_position_embeddings


print()
print("Document tokens:", document_token_count)
print("Total prompt tokens:", input_token_count)
print("Requested new tokens:", max_new_tokens)
print("Model context length:", model_context_length)


# ---------------------------------------------------------
# 16. CHECK THE MODEL CONTEXT WINDOW
# ---------------------------------------------------------

# Make sure:
#
#     prompt tokens
#          +
#     maximum generated tokens
#
# fits inside Qwen's context window.
#
# If it does not, stop with a clear error instead of
# allowing model.generate() to fail unpredictably.
assert (
    input_token_count + max_new_tokens
    <= model_context_length
), (
    f"Context window exceeded: "
    f"{input_token_count} input tokens + "
    f"{max_new_tokens} generated tokens > "
    f"{model_context_length}"
)


# ---------------------------------------------------------
# 17. GENERATE THE ANSWER
# ---------------------------------------------------------

print()
print("Generating answer...")


# We are performing inference, not training.
#
# torch.no_grad() therefore avoids creating gradient
# information that we do not need.
with torch.no_grad():

    outputs = model.generate(

        # Supplies:
        #
        #     input_ids
        #     attention_mask
        #
        # produced above.
        **inputs,


        # Generate at most this many tokens AFTER the
        # existing prompt.
        max_new_tokens=max_new_tokens,


        # Deterministic generation.
        #
        # We keep sampling disabled because this was part
        # of the stable CUDA configuration established
        # during the previous debugging exercise.
        do_sample=False,


        # Mildly discourage repetitive output.
        repetition_penalty=1.1,


        # Explicitly specify the padding token.
        pad_token_id=tokenizer.eos_token_id,
    )


print("Text generation complete.")


# ---------------------------------------------------------
# 18. REMOVE THE ORIGINAL PROMPT FROM THE OUTPUT
# ---------------------------------------------------------

# generate() returns:
#
#     original prompt tokens
#             +
#     newly generated answer tokens
#
# We only want the NEW part.
generated_token_ids = outputs[0][input_token_count:]


# ---------------------------------------------------------
# 19. DECODE THE GENERATED ANSWER
# ---------------------------------------------------------

answer = tokenizer.decode(
    generated_token_ids,
    skip_special_tokens=True,
).strip()


# ---------------------------------------------------------
# 20. PRINT THE RESULT
# ---------------------------------------------------------

print()

print("Question:")
print(question)

print()

print("Answer:")
print(answer)